apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        env:
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        ports:
        - containerPort: 8080

# Here, we're defining a Kubernetes deployment for our application, specifying the Docker image to use, setting environment variables for MongoDB host and port, and exposing port 8080.
